version: "2"

linters:
  default: none
  enable:
    - ineffassign
    - errcheck
    - misspell
    - unparam
    - nestif
    - govet
    - revive
    - prealloc
    - depguard
    - dogsled
    - dupl
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - nakedret
    - rowserrcheck
    - staticcheck
    - unconvert
    - exhaustive
    - copyloopvar
    - err113
    - unused
  exclusions:
    paths:
      - testdata
    rules:
      - linters:
        - gosec
        text: "G204: Subprocess launched"
      - linters:
        - err113
        text: "err113: do not define dynamic errors"
      - linters:
        - staticcheck
        text: "ST1003: struct field Https"
      - linters:
        - staticcheck
        text: "ST1003: struct field Id"
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  exclusions:
    paths:
      - testdata
  settings:
    goimports:
      local-prefixes:
        - github.com/nakabonne/ali

run:
  issues-exit-code: 0
  tests: false
