linters:
  disable-all: true
  enable:
    - gosimple
    - ineffassign
    - errcheck
    - misspell
    - unparam
    - gofmt
    - goimports
    - nestif
    - govet
    - revive
    - prealloc
    - depguard
    - dogsled
    - dupl
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - nakedret
    - rowserrcheck
    - stylecheck
    - typecheck
    - unconvert
    - exhaustive
    - copyloopvar
    - err113
    - gofumpt
    - unused

run:
  issues-exit-code: 0
  tests: false
  skip-dirs:
    - testdata

issues:
  exclude-rules:
    - linters:
      - gosec
      text: "G204: Subprocess launched"
    - linters:
      - err113
      text: "err113: do not define dynamic errors"
    - linters:
      - stylecheck
      text: "ST1003: struct field Https"
    - linters:
      - stylecheck
      text: "ST1003: struct field Id"

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/nakabonne/ali
  misspell:
    locale: US
