name: test
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - '.github/'
    - 'images/'
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - '.github/'
    - 'images/'
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build
    - name: Test
      run: make test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
